jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build with Maven
      run: mvn verify
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
